# Generated by Django 3.0.2 on 2020-05-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remind', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remind',
            field=models.BooleanField(default=True),
        ),
    ]
